name: streptopelia_orientalis
description: "Time is money."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  # 状态管理
#  flutter_hooks: ^0.21.3+1
  flutter_riverpod: ^3.0.3
#  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^3.0.3
  # 请求
  dio: ^5.9.0
  # 系统分享
  share_plus: ^11.1.0
  # Log
  logger: any
  # 图表
  fl_chart: ^1.1.0
  # 本地验证
  local_auth: ^2.3.0
  # 数据库
  drift: any
  drift_flutter: any
  path_provider: any
  # NoSQL
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # 屏幕适配
  flutter_screenutil: ^5.9.3
  # 弹框
  flutter_smart_dialog: ^4.9.8+9
  # 动态取色
  dynamic_color: any
  # 路由
  go_router: any
  # 国际化
  intl: any
  easy_localization: any
  # 底部导航栏
  salomon_bottom_bar: ^3.3.2
  liquid_glass_renderer: ^0.1.1-dev.10
  liquid_tabbar_minimize: ^1.0.3
  # icons
  iconify_flutter_plus: ^1.0.4
  font_awesome_flutter: ^10.10.0
  # 模型
  freezed_annotation: any
  json_annotation: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 应用名称
  rename_app: any

  # 图标生成
  flutter_launcher_icons: any

  # 启屏图
  flutter_native_splash: any

  # 代码审查
  flutter_lints: ^6.0.0
#  riverpod_lint: ^3.0.1
#  custom_lint: ^0.8.1

  # 代码生成
  build_runner: ^2.10.4
  # Riverpod 代码生成
  riverpod_generator: ^3.0.3
  # drift
  drift_dev: any
  # hive
#  hive_generator: ^2.0.1
  # 实体化模型
  freezed: any
  json_serializable: any

flutter:
  uses-material-design: true

  assets:
    - assets/icon/streptopelia_orientalis.png
    - assets/translations/
#    - assets/png