name: streptopelia_orientalis
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  # 状态管理
  #  flutter_hooks: ^0.21.3+1
  flutter_riverpod: 3.1.0
  #  hooks_riverpod: ^2.6.1
  riverpod_annotation: 4.0.0
  # 请求
  dio: ^5.9.0
  # 系统分享
  share_plus: 12.0.1
  # Log
  logger: any
  # 图表
  fl_chart: ^1.1.0
  # 本地验证
  local_auth: ^3.0.0
  # 数据库
  drift: ^2.30.0
  drift_flutter: ^0.2.8
  path_provider: ^2.1.5
  # NoSQL
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # 屏幕适配
  flutter_screenutil: ^5.9.3
  # 弹框
  flutter_smart_dialog: ^4.9.8+9
  # 动态取色
  dynamic_color: any
  # 路由
  go_router: any
  # 国际化
  intl: any
  easy_localization: any
  # 底部导航栏
  salomon_bottom_bar: ^3.3.2
  liquid_glass_renderer: 0.2.0-dev.4
  liquid_tabbar_minimize: ^1.0.3
  # icons
  iconify_flutter_plus: ^1.0.4
  font_awesome_flutter: ^10.10.0
  # 模型
  freezed_annotation: any
  json_annotation: any

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 应用名称
  rename_app: any

  # 图标生成
  flutter_launcher_icons: any

  # 启屏图
  flutter_native_splash: any

  # 代码审查
  flutter_lints: ^6.0.0
  #  riverpod_lint: ^3.0.1
  #  custom_lint: ^0.8.1

  # 代码生成
  build_runner: ^2.10.4
  # Riverpod 代码生成
  riverpod_generator: any
  # drift
  drift_dev: ^2.30.0
  drift_db_viewer: ^2.1.0
  # hive
  #  hive_generator: ^2.0.1
  # 实体化模型
  freezed: any
  json_serializable: any

flutter:
  uses-material-design: true
  assets:
    - assets/icon/streptopelia_orientalis.png
    - assets/translations/
